# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82ec9fafb8f5bb3070c8be66431ee5433f8ec78d0ef2071898aba103ad6674c74eecbf6407123fa36be40f13520cb166ff86cc91c8e6fe89fde01c257c92d015

test:
  secret_key_base: e4d6493ca96b7cdf686d68bdbd1048074024cb0f2e40c07885e429f0f7a51b7421328ebad85d20910a98def63446465a1e855d61976e6821a1f1dcbf573c698b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
